@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor simpleServer
simpleServer ++
simpleServer -> TCPServer ++: create(portNumber)
TCPServer --> simpleServer --

simpleServer -> TCPServer++ : init
TCPServer -> Socket++ : create
Socket --> TCPServer--
TCPServer --> simpleServer --

simpleServer -> EchoServer++ : create(TCPServer)
EchoServer --> simpleServer --

simpleServer -> EchoServer++ : start
EchoServer -> TCPServer --++: start

TCPServer-> Socket++ : listen
Socket --> TCPServer --

TCPServer --> EchoServer --++
EchoServer -->simpleServer

simpleServer --

loop
    EchoServer ->TCPServer ++: poll
    TCPServer -> Socket ++ : poll
    Socket --> TCPServer--
    alt #Gold client connect
        TCPServer -> Socket ++: accept
        Socket --> TCPServer --
        TCPServer -> EchoServer --: onClient
        EchoServer --> TCPServer++
    else #LightBlue client data received

        TCPServer -> EchoServer : onClientRead
        EchoServer -> TCPServer --: readClient
        TCPServer -> Socket --++: read
        Socket --> EchoServer++--
        EchoServer -> EchoServer : addToSendBackQueue
        EchoServer -->TCPServer ++--

    else #Pink can send data to client
        TCPServer -> EchoServer ++: onClientWrite
        EchoServer -> TCPServer -- : sendToClient
        TCPServer -> Socket ++-- : send
        Socket --> EchoServer ++--
        EchoServer -->TCPServer++--
    else #LightYellow client error
        TCPServer -> Socket++: close
        Socket --> TCPServer--
        TCPServer -> EchoServer ++: onClientError
        EchoServer -> EchoServer : cleanData
        EchoServer --> TCPServer--
        TCPServer--

    end

end
participant simpleServer order 1
participant EchoServer order 2
participant TCPServer order 3
participant Socket order 4


@enduml